steps:
# Build Docker Image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${PROJECT_ID}/sit737:$COMMIT_SHA', '.']


# Docker Push
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/${PROJECT_ID}/sit737:$COMMIT_SHA']


- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/getdoc', 'getdoc=gcr.io/${PROJECT_ID}/sit737:$COMMIT_SHA']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=australia-southeast1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-1'